apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    AIOSTREAM_ADDON_PASSWORD: ENC[AES256_GCM,data:VKFV/HYtVPx/vevx5/isg2sCXjCR8DgH,iv:qFa4afCwcAOqEqGz1cDHjFGThbOClErUnW3Q6QEbQAQ=,tag:yhdo8XrM3+pd23/KWz1tOQ==,type:str]
    AIOSTREAM_SECRET_KEY: ENC[AES256_GCM,data:x/lnS8oE55SAWI8Kin4R3xhMnNh3TvsU65GusrBkvzfIxhnrSgJEIys+kBXGY/VclOP0qajjVV++0oIKZLqfnw==,iv:zKN0FUjKEFF9MA6hsXhgmkkx5zV9YZDAcZVZsc2KkW8=,tag:QL3qWTvlWi8HsyB/Fy3bcg==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:U66Yk/gQuaBnxm9YUNLlQInhMFe4kq2/6xSl0ZeZj8ipOIiH,iv:ahZN+LBrxwmo8onK5M4gVXqn+In1+lY97s2PVOvluVI=,tag:+rUC9wPc17vPQeiMJ1rJUw==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:qbmmh9o0S3i/PF2LbfBwm2wnLCwEbIbz3lm/rJsgcuLdLXdLx6Q65Q==,iv:qTS7Bs5zkakyr/p4wD1JdzNEkUOQ1sScDS8CdwzJ0Y8=,tag:Xn96svKJmLYHVMGhmf3O+A==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:AdGXtHkprbX+lELR805UjDNLghOFsY0PqWl6WZykyOsWQrpV,iv:Sea9MLG+MTWHG+W38jyc+cW2NdDOCo0DT7nyRHxXQiM=,tag:ZbsLzUGv326BiH4U4ChOuw==,type:str]
    CLOUDFLARE_CERT_MANAGER_TOKEN: ENC[AES256_GCM,data:g7LiH9/aO3bANhCAuhqRdhEmtcqysvJ52xpAG54RYVsBwACpDCczXQ==,iv:3X6GzBSaacr5+B70WxToe18Dwnzy1EKX4ZzMnn+MnZ0=,tag:SIV/B/NZseM95HkPuy+eAw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:AiFLdjg8SJ3veYeBYAtxFO7MpLBO/lr/aIzVyuTDP4UGQnXMBBQ766eEXws=,iv:tZOfztJyKVrqF9GO7i6nDfhlRC51yJ2XKSFvX1NjBPI=,tag:soKSTUPBHuDeaMrVyC6pxQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:h2EFoM91lT016mbMhlgsA0MQiw==,iv:aT7RgLrZmv1Tu+etAYl5quqt9ND/zAVQGdiBUD852s4=,tag:vFO0/mQAp6GAoVLQtsf5fQ==,type:str]
    SECRET_DOMAIN_0: ENC[AES256_GCM,data:9N3vrcklXS//sxzHAg==,iv:IYZF6kbCY3OyGAUrBLAA7U9Bbu/0RxjOKxvAc7nYwuU=,tag:4Jex9LFHk7ceqztMjauKww==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T0UycUlIRW5LREcxVVda
            U1dGMWF0WUNFNFNSNXVyLy94QjZLUWxuQ1VJCmRjRG5hTkx4aUpmYy9JMENKRE5F
            YU1hbU1OMmFCc2ZyY3dQV0kyNlVIcU0KLS0tIGFyaUJhd1Q5aUlHamF1bU9Va2Rm
            clhyVWp2ck1vMWpaS2V3Q1hhUFNPc28KdgAx2C+cyoM5pgL+bL5ESm7vzimVedhG
            0JgmAVJ3boOsy4u1uvKMz+F8/DmjlyGHzx39EL2j55XP+ClIpqGl3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T07:13:05Z"
    mac: ENC[AES256_GCM,data:4P72nAfjkOByjhEPvTLuBhxo6I9BP4rrKGM3dzMGU+mQISrfOjSQMsQU0A+0i6/TS73kS3lsuHyoJ2uNTVo5e13IzFR8JEYgER9qfD3sXKo7+B4zmnBLWcKigmdQTcQCCHGDjd9GM8FRiZHOpoE5gqnm9oJKmpyCm3pY44ptC4Y=,iv:UQCioVsp6FD/g2QH7LJwblRoWk9UE1psePlzFj5DV98=,tag:J9tfmnz7aKmYrJjMU5A88A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
