apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    AIOSTREAM_ADDON_PASSWORD: ENC[AES256_GCM,data:N59ovscdcVXlWIu+mONfaYw2EWdzZ1RZ,iv:mSa1DvVlb6w/AHedvGonfGqygy/zAAFHx5zvElB2XhE=,tag:nuevlThOqN+Hu2Ey3amAhw==,type:str]
    AIOSTREAM_SECRET_KEY: ENC[AES256_GCM,data:l2l35ctWu5RunTBTP/FsES6Vh/uKM8PStxhSeO/Xp2srJhMr/xw8XnxhSedlBnlpDWH21H+Y3sFjvT5+FqpjiQ==,iv:HuCLo7zq8Erqu2MYo/V3CwOHr03L+2cCujK+XBfbrFk=,tag:MLLh1GkB9xVHg1tZv3HPRQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:7Hn+rhhXn4xPEiiVO8XAvVKr2seg8aM7AzGGONLSe7Y=,iv:i6GzVSsyoPVLqkdcnlcUMtbY6cAywlJEppQIR0JU5MQ=,tag:uORVwQLxBquzVAByqHQK1w==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:nRBwTRaqmXWP3ZbQfofcFQvcI7ydsDVZqkXuVh2dZ5332N1Dc1Mk6619Xdybv8hdHCSg8a5hqD+Vkze+73r/NA==,iv:o9j1HVoO7Sf6zGBU6lNGFtZdCMZ/eFsW0NXyagQKxJg=,tag:8N/OQi5Xpd0hAsv3JW6qhw==,type:str]
    AUTHENTIK_OIDC_CLIENT_ID: ENC[AES256_GCM,data:RYI9YC60QrKxZSoye7+Q3AgFYq7Vj8hpZNWoD+wxdSE6IyPy,iv:5FYKb6vZLhiUt+qCY9YjLYllttzkpQLmvMD3O6otsKQ=,tag:uxBi8nf0FxvW+Y4p4uoFPg==,type:str]
    AUTHENTIK_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:tvPY+2Pe1jKpe0CozMcNqwGJIXSGlZ4CIhyVFqmG2NHbs1SCIap5cvI9CaXTJsa3+o2tjq4NDbXFjexTn349fA==,iv:+ZNkvIev+gH8xgA34SfclU1HeZF+zNg36smWP/hYzZ4=,tag:tA0VXzotMxEKhgNsFV2GWQ==,type:str]
    AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:K0aCi9zLHU99JMlCSuI6X3RUWec=,iv:X05mvDxNRlmUC10X7i7rh9IA6GMHqJfYXguxdUnEWL8=,tag:zrEuT3pksCxXkms6vYAoPg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:T+sfnUoxGwMEwOM4Mh0nZCPJ6Wuzxc8pJ3bDd9ZNQP2MRlHDKXHIpwHAqelKTn4OLCSj4UN5/lKbT4b7koIhWdXpejOMthZ844kKv7uixLqRN314LbZkAItgMb0oP+K5dWupBw==,iv:bBHm1YaMQSVCv0Rklku6iFQVa0apQuqXmK6LRTPp3Bc=,tag:FkSY/CJx8Fgbfya+anNqRA==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:Ewu7j6u9jLNU3zbQagl5q9Zoc3LXfb/qt2zPaKQclCGOJ2Ky,iv:l6Qq+sMUda5gCjAOqTCR3NdkO/p/6bUR+XO7vDq3nAw=,tag:bWh8X2jtREUr+/FGqgp9KQ==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:FnC9spYVKHk+b1dcmYLt0Lxx0vWA18mQT2sKKjVk/k2uOzFju5RKZQ==,iv:pN0twpprb5Voy79na7TKjW3OnimYD1Q0tbQ+d0Mi7wc=,tag:nRCWG379qlSlD6foSDZsxQ==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:IxkQTmEwwoPfkd90HrV/usaeBJFLXm7WI3/p5sn/8CWqZADN,iv:bcIhz0VPd0uPN1nHoCWVWVIV6jOAaaQGjc8jk++4hQQ=,tag:cu8wvu2Tu8/1R60EBG6yuA==,type:str]
    CLOUDFLARE_CERT_MANAGER_TOKEN: ENC[AES256_GCM,data:5sjjLDmTW9xdL3Irc8gZuX18puTEFIYOBu/lgEUBm4hdu9KEGo6PGQ==,iv:67pK352AVhJ9HWJ/kAqjf6iAOS+cV97ozd1GpraweCI=,tag:z9GCAkttkFfEjYSzpdYkjw==,type:str]
    CODE_SERVER_PASSWORD: ENC[AES256_GCM,data:+PxzxB52v7gny+odb74A2hBsPfzXBQ==,iv:/cq+acTEn9rN6DDtxJPNXb72XAl+fIofcBMQldksXMY=,tag:2RwcSFUIJMIqwLPO8XDEOA==,type:str]
    ESPHOME_DIST_CLIENT_SEED_VERSION: ENC[AES256_GCM,data:LilJBs/TCs0=,iv:vWhukwtNoHhDZqtabNxflkDxxn79zJ4n5oiGlPqQEI4=,tag:4dbc32GwVxTZL3kLaMiHIQ==,type:str]
    ESPHOME_DIST_CLIENT_SERVER_TOKEN: ENC[AES256_GCM,data:+YYtF1jPmVqJKkWcr9z6N79DwMWoVJvz7waYd22r4jI=,iv:V2kPQ2Lr7hE9YqGre1HIWuxwzBONQucyAcUygFeZXH4=,tag:5OxkZC9TWC+TRDjIBw6T2w==,type:str]
    ESPHOME_DIST_CLIENT_SERVER_URL: ENC[AES256_GCM,data:gVp+3cLBWvn5jncVgnz2dJrxsuZPu60=,iv:FMeo/jmn0srA0GwfIChYRj3T/B7pysWluZbg+6UhX+A=,tag:s3mqhNDfgTQT5mUO2Pvx7A==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:PYNlcrAlMppnHtXaejMj/Q0l4mtfyBulMg0zevwrmwHrxs4Gaom6HdzeZZI=,iv:uANqchno4wyI7lq18rcpe1gNtD4EyhhI5Yfsu3gHz94=,tag:mKDMHsTTtHoU3vTlaJWigg==,type:str]
    PIHOLE_WEBPASSWORD: ENC[AES256_GCM,data:GeFCEbVOm8MEgawJ,iv:wcWnMBPounmStD2BCtSKgoUa4fSphOC4GLhZ7bAKJCc=,tag:+ivrAxG8Av0ztmqUBFUghA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:hbeKOfzV+29vX9cbM5pX+D2oiA==,iv:cHCgFXupZv+FIgmKtSBvAwHyN2mqfsQWPusZ0Gy6mJE=,tag:bo5Ra+Kol3qex8jkJFKj8A==,type:str]
    SECRET_DOMAIN_0: ENC[AES256_GCM,data:Fdh8b4/Cf03Xb6KjZA==,iv:HsK93bo0FkD56SctS1o7U7hrwVjKWFHVSDCt9ZkKwNA=,tag:Mu+7WZ80dASsI0QOOrLeqQ==,type:str]
    SECRET_DOMAIN_1: ENC[AES256_GCM,data:J4Lnj42YmtydCxIM9uw=,iv:W7VHrAA2r/SropT2U88jQy/yXVSgTwjVISwfMIr8iXw=,tag:0zqrhjyDjOQyITYeiCBmBg==,type:str]
    TZ: ENC[AES256_GCM,data:cm0H1dljuSQOnpxz10rSCA==,iv:gvl6EZFzJLppwnq4z/agmOL2PYpCKJG4po9kV/ytwUo=,tag:vICXFmQkhzvHYWgVxywO2g==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:M/y6+B4=,iv:cCNPrdizPWBBeC99kCetZfv7ggfXxaM04qHy31IisFk=,tag:6UECEfsQv1ET+HQufLlXtQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:GNizhy9r3riY0agu7fz3JpnxLYLOMA==,iv:b6P3Ih0zJG9mM7KxJ0kB4btTz6J5ZNu4tNbC4ygUYKQ=,tag:r1U6Z0hhdLSLT48dFZQI6g==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SWJpSlp6elg0bFhRS1Uz
            WUlIV3phT3I0UG5sM0gyVUtia3hXa0xoZ1MwClNQdnFVaWEyaFNCb09jSlFJKzR1
            c3lJaEZxWWYvOUxLRHJkL1JEMFY4bjQKLS0tIFdMVld3Ry84MXR2MXUyVWczbVY5
            NC9CUFU0N2o2N21pM1dqZU90cG1hTVEKbPjddyWmSD4Z2MigFQidXZBc4SYPtSKN
            hjx44JKEpzuyiFkxBBMZNiiztqN8/JeOrbF3mUTeyMfCTt9AJsStyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T21:32:58Z"
    mac: ENC[AES256_GCM,data:TZSNODBfOhzrXR4iueMQo/Cz8vvo8uRcUKauthCoMNiQJsFbDsro1DUWfGJzt9W5oFQzE8r0GaBL91NgItenMDQ9zsocug4DetmDsbvlZjLoljakpHRfHLZZL+NY3JynWjoOHKf/LJB9vi+db2XmMoAevIYmLdOkbKv3h+9sYRI=,iv:QnxyXnpCJu5lY1tj3WAWdUi5TXmPFU4z2l0klTEvAmU=,tag:30QJyccT8YC6dB0t+iGdyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
