---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: platform
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Platform Project
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: platform
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: apps/platform/**/system/config.json
        repoURL: https://github.com/Myrenic/Orbit.git
        requeueAfterSeconds: 20
        revision: "main"
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
  syncPolicy: {}
  template:
    metadata:
      name: platform-{{ userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: "{{ destNamespace }}"
        server: "{{ destServer }}"
      ignoreDifferences:
        - kind: "*"
          jsonPointers:
            - /metadata/annotations
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /metadata/labels/app
            - /metadata/labels/app.kubernetes.io~1instance
            - /metadata/labels/app.kubernetes.io~1managed-by
            - /metadata/labels/app.kubernetes.io~1name
            - /metadata/labels/app.kubernetes.io~1version
            - /metadata/labels/helm.sh~1chart
            - /metadata/managedFields
        - group: ""
          kind: Namespace
          jsonPointers:
            - /metadata/labels/app
            - /metadata/labels/app.kubernetes.io~1instance
            - /metadata/labels/app.kubernetes.io~1managed-by
            - /metadata/labels/app.kubernetes.io~1name
            - /metadata/labels/app.kubernetes.io~1version
            - /metadata/labels/helm.sh~1chart
            - /metadata/managedFields
      project: platform
      source:
        path: "{{ srcPath }}"
        repoURL: "{{ srcRepoURL }}"
        targetRevision: "main"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
status: {}
