---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-external
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
  externalIPs:
    - 10.0.100.11
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.tuntelder.com`)
      kind: Rule
      services:
        - name: home-assistant-external
          port: 8123
  tls:
    certResolver: letsencrypt
