---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-external
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home2.tuntelder.com`)
      kind: Rule
      services:
        - name: home-assistant-external
          port: 8123
  tls:
    certResolver: letsencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-external
  namespace: default
spec:
  ports:
    - port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant-external
  namespace: default
subsets:
  - addresses:
      - ip: 10.0.100.11
    ports:
      - port: 8123
