apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home2.tuntelder.com`)
      kind: Rule
      services:
        - kind: TraefikService
          name: ha-external
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: ha-external
  namespace: default
spec:
  weighted:
    services:
      - name: ""
        kind: Service
        weight: 1
        servers:
          - url: "http://10.0.100.11:8123"
