---
image: "ghcr.io/home-operations/sabnzbd:4.5.3"

ports:
  - name: main
    containerPort: 8080

ingress:
  host: sabnzbd.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: authentik
      namespace: edge

envs:
  - SABNZBD__PORT: 8080
  - SABNZBD__HOST_WHITELIST_ENTRIES: sabnzbd.tuntelder.com

pvcs:
  - name: sabnzbd-config
    type: nfs
    server: 10.0.69.20
    path: /mnt/ssd_disk/config/sabnzbd
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /config
  - name: sabnzbd-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library
  - name: config-file
    type: secret
    secretName: sabnzbd.ini
    mountPath: /defaults

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
