apiVersion: v1
kind: Secret
metadata:
    name: azure-backup-credentials
    namespace: storage
stringData:
    AZBLOB_ACCOUNT_NAME: ENC[AES256_GCM,data:EhfUtZMI66+sSFrr2tPmm7qH,iv:JIS0kW23vfsCE6ffJ9nULq0VpSg7/DFSYBTjN+VYF7g=,tag:ovOaYq5JUpDqSTwZ9U96xQ==,type:str]
    AZBLOB_ACCOUNT_KEY: ENC[AES256_GCM,data:z4feqhjzHTUfLdzszscn87aIl9FahxvDx6cd3Ll94z1X8woJ9j2b1PMJBKBYzx9chx+zvTjg59nwO0vbt3YcCjfcMDqOxXwruzE8GDfdtRKtMMoyLPWNog==,iv:K6i1uQ7/pxHNlmHG4gFbB7oGIHB1Ve4TZEkUVyTULKU=,tag:YYMnxuliFlwW4EhTj5G9yw==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ3FyUUpDanY3RUlpbGt2
            VFN6NlA4TDNaVFNsRkNCYTBURVQrOG9qSmtFCi9veE5mQnZBWVFsZElwNU9jbGlF
            aXpNM0tZQlNOc0tjckdPM0VhVHE1Yk0KLS0tIE9nMGdTUnRaYTAyNmJNKzdTVThn
            dFlwc2hNd1FVRVlTaGk3djRoTlBBcTQKel1VpTvXUTy5o+/3Dl11rZRKx8xjl4Ew
            EN0gO16Y1P1fsXyDC26LrqasdAkzRsJoyJifp4HmAoK51eLedCU0dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T09:18:26Z"
    mac: ENC[AES256_GCM,data:6brYIW5tv4RKW4B8QQq2pfZkLlsrRBMq/VqwHHXuLdW4W4l7+Lq1uxZfYxnyJ264yFzMVcrcu9N63yH9e9A7VPLQbLrOdmRwyyP88SlVGz9TQYcZbp8DYRJkSxrNE65+hVxuuyWq9MEWSKD3RL6PGu6MBw0l8XcYR4gHcllICK0=,iv:XB0Uo/pngbPC2s7YhJ9ELoaRwxwyFjBx7CXJPl19YNQ=,tag:qg6utdxW5B6vlJQmn8JPjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
