---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    namespace: storage
    version: 1.10.0
    includeCRDs: true
    valuesFile: ./values.yaml


resources:
  - ./ingress.yaml
  - ./azure-backup-credentials.sops.yaml

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: longhorn-uninstall
    patch: |-
      $patch: delete
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: longhorn-uninstall
