---
persistence:
  defaultClassReplicaCount: 3
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: true

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

defaultBackupStore:
  backupTarget: azblob://longhorn@core.windows.net/
  backupTargetCredentialSecret: azure-backup-credentials
  pollInterval: "300"
