---
apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: network
  labels:
    app: traefik
    observability.orbit/component: traefik
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
  selector:
    app: traefik
