apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
spec:
  encryptedData:
    api-token: AgCgUH88JYN7HRYyQCPdIxdveDtH4E6sP1MsjNKuJDE9rlJx0QcDKSAiqQx93qJCpm4C2Xxt42EnZvVaB9ZwtqVB6IIn8PtNR6mKvCtBa+9R9QMLOvmoIuxPoXatYKEiZonlH7Kteh9rEVfLv/a2NbXJF3TISfMNH/JMDv30+PTjlNMJh61hEItuYYarlYPzDdLP1CiyWZDyUzIWdF8lp8ovobH7hKN0x2n9SYNKVKlhvDMT5vSkL1QgXjdm4pYVchOu8qKRC13uY8r3pYje8omlzvq72MACIf/A4dPkR9d5ZGApuQoOAUjupt5jRTFROKFOi8OoMrp7Aac9vCMwT258OBgfDY/Og+jGohl6W4jd0DHHK2BG5MWoKgHAjJATC2zlYuGuly8N8sAGgavsuJxiwZaEOFlpatqbigTFqBKd3MMFC4WqTObGs6diixkO5AYc9oCkflATdQCHr11lNJZ1PTKOvhyBAi8It+X1uxJTfZx4CS3eqwH09AfZPi9sG8DerAUEo/i7fnGubVHxFb3B1riDdeTl/DI5P5qMADGxL04JQBV+E2iwxQoJFyspDgjIdb0gQd8t9t4KAFTNk+oG//ycPUFmW2m7WYMY9Erklh7k9JiaW01fRJEVX+IkVUhYxGh8b+IYbV4SMHSeFAFgJgcGnEqvdQ8EKY7OcrohHJ3i515WY3LIMlPN/+YxrFWyuNsfi0zzIDvecEVIR2FX6JkmPxEv8BIaV3+pUAlSWJmpUTxJFhb6
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
    type: Opaque

