apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: sealed-secrets
spec:
  encryptedData:
    api-token: AgBpnVVj6LEr2ea9mMKt6wxQAqpxWSZcwGJZ/7/8VDbmwMbIoAf0s7jrsEOC5J57PY59LoAtpvCjflKONljHNzyb5QTy7r7eFIZX1hHVyLZNZt+LzYdjxgK8sxqmPUEpJKlw5BDtVTrcxSTj9jCcUGGxBAknhyvQdDf8FpJHqeagRq0FAYSsDuBYMTbhQnuiq2ZrhClRrZQW5AZEg5llbo9i6ZfpVUUY9WiAMlK81ZiTMuSuTebsgbhwuA5TLAGXw7EjVdS2c2NxyL+5kpjyq878lb40U/DOZVnK+PhbFeU6FCII4ZSeswEJEfAClLV9HDKUc8cpNp0ulfmcfsuRJdS+YQ20VxnXuyd0sVIfGGc8Kx2se+eWKjk4Azu/Y6Z/q600UBlxDmmA2JJghbzrR+FuvNDQD7zhtrM7UVLrvEpLO9mROCjViFe6+1f/vQYZHBhOgP/0L1/GE1mSdN3yIpB6haSAyEiJQiXRxWvPVQP8Th+1rzmTLEWQns8BraznZfjKZQ9BmvfeBv2VzYAqgbMfZGbCNLZYjFDAgqmn00INp+3mVL+y8WDnA9bykhOyakBSVsmV7cm7W6bamAxHvzlcU7z5To3cWpTyslBQrpaIl2FCsWyXgiAGym0rPdwVMTNhv/gWMAiDWiLWtUsqkMorx3Ix37qg0B18EuSHf5tjyWruGn8IZnDB6R6dIrUMGlHnuv6FsH6Y2s3OW5UxXvQL2mHXLRDE7TnsGyyqwZg60wtuMnbnxXCZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: sealed-secrets
    type: Opaque

