---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-api-token
spec:
  encryptedData:
    api-token: AgApFX3p5rlHvCxz1T7XKIQ9YGxJ+wlqnWOKRszAtPx0IpwglNK7dJDKZ3fpZHFMtzSGPUfbgbD/hAmFPYF/JfIVHSocOSNWBhX4S/LAtzSn3wS9usAgdHSAvKWwuz69j3FD0JF8SCsRQs75Gk8SpB1UKKMCEBLl3sw67VmhIS42j8SzX7YWG2gpQHyr05ay5yjfTPld5wv63arFMDLnhKbVoeVs6MBUAHFaYMu/OJjjhCJYPmKddfZ0cHfpdc8U6VhRtb7F5h/pUYPsHk3dD05/iqcj54EJW7fBrKpC+x8JlgX4YSQX+Wm10Oz1C/Ss/c8KpGBMot9Q27Swsr+PvkfsVWOOwbj8nc0Q6lzQkZjTrJwN/HKlUJePa5ODcae0VZwXKYrRrMDSjXCyZlZr9aitFM5i1Gpf3eI/0QMAQZttoPdn6JeIAfGj+algXH5j/pIJGx6exSPFupFeh/eQMoxmTwPSqXXowrhxSfxcw/vX/4qE+L/CvRqj3o942E3g4TUbxvqSadKZYsYsgsmiD2V3QZ7FH4VP8qSz4wnox7EqUvCJgqIthgsw4qcRYubV5m9HIkDk7v6CGDVKyA3gzWfJ7RX6OjAqqkh0kqnFHM2Kez9wgwuZ0t0pzDJpcSBuyW1aIUrwonMx3EXYT6wOryzhfcXi2axiPxFGEXiw8KMbzkK2rwqOYVwbufb439Qxzarj3HXo+yOFoDiIGOR+mDOkiRNciiepLYWBaVuc01oShhO1qh9tz7Z3
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
