---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
spec:
  encryptedData:
    api-token: AgCKdV/zP1mGJClqZQwuKAyJLSTiq90GTkoyN0ADBRTz2HLwP/JbUANwkcXLHWTMyXf4Cwj2fxt7r85hhMBJoVmDHnKsYi34xALdqQKxYjCZrmT2z5sIZxYQ1QFThT48cdVpuRsw6hpSbuzGNTDIatooXYocH+1abaojxnnvrt0umtEX41udDHz2IkEbO0O6bmimHY0cRSRYZDC/Q2TY4wlRCxhdtrdS7AlLKlq2ntg8BhlisM/KZQ73QndYGgUMO9rx89LH0Ezch24JS1AlMc9n5ER6XuTi5WuSRP9rVTyvBIZ0xKrPfbG4YpFiW6RXu84RpgScaOHGEzwbRwh4gmUlGePTJPAHK1qqDTQ2Yf0QlrpJUqNMQR8tG8kNSYL1XlzQOA0ChGDf16VcGGvf27lSarlmUM+MIvFbIMHiHqPHIWvwtDaTsi+KvbfD+ROHEO/LS19lIu9e1j9Ao4zMj/nbVbug504QS4x74RxL0ItfkB04HE6TxQQ62w9lG+wsBJzCdw5DXktkufeGfJmRIHDRtK5NNGkU9b2uEHQ82ICCNamlL7Vygc7cvklQCdcu6aBFOh+Vuh5IqgOZnCWVJF416wPR/rxBkS197U2rXXa6ic7q0318Xc18t4c//Cbd/8ir86rQxeltthEIBGauRoQHx1uF3QbEz4jeXseHaVIN0dsE9NrQanldh3CqnuCn4iIKR5wNr++Hrg+/vaMaEeOiq/QYJ03W1D/BHx1nSNaRXjUgPdFi2g84
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
    type: Opaque
