---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: network
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.69.100
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443
  selector:
    app: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingressroute
  namespace: network
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.${SECRET_DOMAIN_0}`)
      kind: Rule
      middlewares:
        - name: oauth2-proxy-auth
          namespace: network
      services:
        - kind: TraefikService
          name: api@internal
  tls:
    certResolver: letsencrypt
