---
creation_rules:
  # Kubernetes secrets (encrypted with SOPS + age)
  - path_regex: kubernetes/.*\.enc\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v

  # Terraform infrastructure secrets
  - path_regex: terraform/infra\.json$
    encrypted_regex: ^(password|username|ip_addr|gateway|url)$
    age: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
