apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-nginx-config
  namespace: edge
data:
  default.conf: |
    server {
        server_name home2.tuntelder.com
        listen 80;

        location / {
            proxy_pass ;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header    Upgrade     $http_upgrade;
            proxy_set_header    Connection  "upgrade";
            proxy_redirect off;
        }
    }http://10.0.100.11:8123/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-nginx
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant-nginx
  template:
    metadata:
      labels:
        app: home-assistant-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: home-assistant-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-nginx
  namespace: edge
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: home-assistant-nginx
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: edge
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home2.tuntelder.com`)
      kind: Rule
      services:
        - name: home-assistant-nginx
          port: 80
  tls:
    certResolver: letsencrypt
