apiVersion: v1
kind: Service
metadata:
  name: home-assistant-proxy
  namespace: edge
spec:
  ports:
    - port: 8123
      targetPort: 8123
  selector:
    app: home-assistant-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-proxy
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant-proxy
  template:
    metadata:
      labels:
        app: home-assistant-proxy
    spec:
      containers:
        - name: proxy
          image: nginx:alpine
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: home-assistant-proxy-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-proxy-conf
  namespace: edge
data:
  default.conf: |
    server {
      listen 8123;
      location / {
        proxy_pass http://10.0.100.11:8123;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingressroute
  namespace: edge
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home2.tuntelder.com`)
      kind: Rule
      services:
        - name: home-assistant-proxy
          port: 8123
  tls:
    certResolver: letsencrypt
