replicaCount: 1

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - grafana.tuntelder.com

admin:
  existingSecret: authentik-secret
  userKey: bootstrap-email
  passwordKey: bootstrap-password