apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CRDs are managed by the helm chart with includeCRDs: true

helmCharts:
  - name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: "23.0.0" # renovate: helm=prometheus-community/prometheus-operator-crds  
    releaseName: prometheus-crds
    namespace: monitoring
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "65.1.1" # renovate: helm=prometheus-community/kube-prometheus-stack
    releaseName: prometheus-operator
    namespace: monitoring
    valuesFile: values-prometheus.yaml
    includeCRDs: false
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    version: "2.10.2"   # adjust as needed
    releaseName: loki
    namespace: monitoring
    valuesFile: values-loki.yaml



resources:
  - volume.yaml
  - ingress.yaml