---
prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 20Gi
    #       storageClassName: ""   # leave empty if using pre-created PV


alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    # storage:
    #   volumeClaimTemplate:
    #     spec:
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 5Gi
    #       storageClassName: ""

prometheusOperator:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

grafana:
  enabled: true
