apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CRDs are managed by the helm chart with includeCRDs: true

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "65.1.1" # renovate: helm=prometheus-community/kube-prometheus-stack
    releaseName: prometheus-operator
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: false


resources:
  - volume.yaml
  - ingress.yaml