---
{{- if and .Values.ports .Values.ingress.host -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "generic-service.name" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.ingress.annotationsPrivate }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotationsPrivate }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingress.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`)"
      kind: Rule
      services:
        - name: {{ include "generic-service.name" . }}
          port: {{ include "generic-service.httpRoutePort" . }}
      {{- with .Values.ingress.middlewares }}
      middlewares:
        {{- range . }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
  {{- if and .Values.ingress.tls.enabled (or .Values.ingress.tls.certResolver .Values.ingress.tls.secretName) }}
  tls:
    {{- with .Values.ingress.tls.certResolver }}
    certResolver: {{ . }}
    {{- end }}
    {{- with .Values.ingress.tls.secretName }}
    secretName: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
