{{- if .Values.secretEnvs -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnvs }}
  {{- range $kk, $vv := $v }}
  {{ $kk }}: {{ $vv | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
