apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true

helmCharts:
  - name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: "23.0.0" # renovate: helm=prometheus-community/prometheus-operator-crds  
    releaseName: prometheus-crds
    namespace: monitoring

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: remove
        path: /metadata/annotations
