---
image:
  repository: "ghcr.io/myrenic/sonarr@sha256:1844d78283b2917aefa1eb281eab6ada4f0f6dbb7e5df2f848ad6d8d7983578c"
  tag: ""

ports:
  - name: main
    containerPort: 8990

ingress:
  host: sonarr2.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: authentik
      namespace: edge

pvcs:
  - name: sonarr-config2
    type: nfs
    server: 10.0.69.20
    path: /mnt/ssd_disk/config/sonarr2
    accessMode: ReadWriteMany
    size: 5Gi
    mountPath: /config
  - name: sonarr2-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
