---
image:
  repository: "ghcr.io/myrenic/sonarr@sha256"
  tag: "94fcfd29db7a5ef98eb0aa54655565259a541c4e28dacba4b0baf4aaee09c93e"

ports:
  - name: main
    containerPort: 8990

envs:
  - TZ: "Europe/Amsterdam"

ingress:
  host: sonarr2.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: authentik
      namespace: edge

pvcs:
  - name: sonarr-config2
    type: nfs
    server: 10.0.69.20
    path: /mnt/ssd_disk/config/sonarr2
    accessMode: ReadWriteMany
    size: 5Gi
    mountPath: /config
  - name: sonarr2-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
