---
image:
  repository: "ghcr.io/myrenic/roomctrlscraper"
  tag: "latest@sha256:06f6c563b896b2a70bc4422f9b781ee7aa62428b06ddd9c8093e8e22940b9397"

imagePullPolicy: Always

secretEnvs:
  - ROOMCTRL_EMAIL: REPLACE_ME
  - ROOMCTRL_PASSWORD: REPLACE_ME
  - SCAN_INTERVAL_SECONDS: REPLACE_ME
  - ROOMCTRL_INSTANCE_ENDPOINT: REPLACE_ME
  - TELEGRAM_BOT_TOKEN: REPLACE_ME
  - TELEGRAM_CHAT_ID: REPLACE_ME
  - TELEGRAM_THREAD_ID: REPLACE_ME

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

command: ["python"]
args: ["entrypoint.py"]
