---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge

resources:
  - roles.yaml
  - volumes.yaml
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - middleware.yaml
