---
persistence:
  defaultClassReplicaCount: 1
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
defaultBackupStore:
  backupTarget: "nfs://10.0.69.20:/mnt/nfs_disk/backup"

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: true

nodes:
  "talos-4y6-uzl":
    disks:
      "sda":
        path: "/var/lib/longhorn-disks/sda"
        allowScheduling: true
        storageReserved: "0"
  "talos-7ye-m7n":
    disks:
      "sda":
        path: "/var/lib/longhorn-disks/sda"
        allowScheduling: true
        storageReserved: "0"
  "talos-dvx-id0":
    disks:
      "sda":
        path: "/var/lib/longhorn-disks/sda"
        allowScheduling: true
        storageReserved: "0"