---
persistence:
  defaultClassReplicaCount: 1
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
defaultBackupStore:
  backupTarget: "nfs://10.0.69.20:/mnt/nfs_disk/backup"

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: true
