---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create the namespace first
resources:
  - ns.yaml
  - secrets.yaml

# Inject namespace into all resources
namespace: roomctrlscraper

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: generic
    releaseName: roomctrlscraper
    valuesFile: values.yaml
    namespace: roomctrlscraper
