---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CRDs are managed by the helm chart with includeCRDs: true

helmCharts:
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    version: "2.10.2"
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yaml

