---
image: "ghcr.io/fallenbagel/jellyseerr:2.7.3"

ports:
  - name: main
    containerPort: 5055

ingress:
  host: jellyseerr.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge

pvcs:
  - name: jellyseerr-app
    type: nfs
    server: 10.0.69.20
    path: /mnt/ssd_disk/config/jellyseerr
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /app/config

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
