apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: geoip-secret
  namespace: monitoring
spec:
  encryptedData:
    license-key: AgAgZUEPc+5qLgyliguLB3Qe5AuYon7XlBuA6LgdO2JFozkvVvL43K1oWomRVf1J+jkGmOR3wUplOABDwtr0/j/mnF+c4pPcLPCIYn9m2rd5DKA/NaIR1urunp9NRhg3sCzMONwr9+dEg38heOJXSZ/2ea/MjsGrcq4aNxgP6P3dfTZHQni1ORST2tmIFsU9iCHYdc2QvTw+63C9vpBET9fke5MzN6hHTb+7Ky4eBppVACRJ1irBxg+61GAPhVyuyYh3B35Q0ve+I32+O6j2YEGmyoyMMnCQ/ej/5/nOrwr4BTK1F2H2g+PKo4ITE9stpGwBOZjQDSafHEhPWpOhiRo66VmHlcZZwtAN5AJxgdNZ45JpCepf629LAF/Foa2Q2lPl/DJukbrEQDAk+BMarcWJw2vaHOrvh5vBEnP9Oj+5N1KSPzJ8YYCHtRTEw+Yb22P1j34H3YaQKLJDlJyX5l09drAVHEGGC5A0r15b9LXfJIZHhKg598SOD1s1fBazqMVyDFrMMjcWWQeOQxGEUJLsZ4dclyKjwdmbWxmGLeVnky6GkKgVO7VRmgAMQ0vCfe7sIEZlp42fWYCkuwPs6tfrBnucC8Dgx4Uq1vQtoLH8HTzjhC0FPGohS7uv9Ik9xsysvhqmvEE6TYNbCpHTNFbTzxp+2ejEfkYWTXRbvGVZ8A72gyD0iy2rWc9NrjFPs2SE04pNzXz84ufKKG4Qf9KJd37Sps6v8DFdwKMKcvAotOHzLfroSqBI
  template:
    metadata:
      creationTimestamp: null
      name: geoip-secret
      namespace: monitoring

