---
# Placeholder — replace the value with your real MaxMind license key, then seal it.
# 1. Sign up free at: https://www.maxmind.com/en/geolite2/signup
# 2. Generate a license key in your MaxMind account
# 3. Replace the value below and seal with:
#    kubeseal --format yaml < geoip-secret.yaml > geoip-secret-sealed.yaml
apiVersion: v1
kind: Secret
metadata:
  name: geoip-secret
  namespace: monitoring
stringData:
  license-key: "REPLACE_WITH_MAXMIND_LICENSE_KEY"
