---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: geoip-secret
  namespace: monitoring
spec:
  encryptedData:
    license-key: AgBbCmz/SEwfBFrgXQdMTrAlGn4q739rEHbjRbFQ4jRYcuZO4JzNzNoKDG+1Dv17JsLPXcmc0a7cZ9nVXrqVVTzFpUgsQcXqwtx7qlhScXw4zx289wBeY/B+RshV//CGOrGw62T6MTQJZ80M7JQ6ymZ2k+TF/LijlVgpviJPZIQdM0MF15lYegFgjg/2JKAMzNyZ9VafDmVS7kT/Za1khTd8JFcJOQNKckeDdHHLNq0gWyTli3hSKlX0HyvnAwIhPL5U/bqD9ivYZLHXT9FxMh5z17VMlBu//JSIQ4JzMgooWN5V1L3dARpfQOCTh+3N2idhHDbxNq2sudAyJxz59Sq1ezb6gpLS+m7gcbAHgQjPapyqTb+QKiIhJU7lscjSE3qH51H69nyAMKQhGk2dE/5gBzoILk1qbBh7d1uMopfldOowuB2Ge2T4h3W1RoYcO2QDHYO8hq/xDt/M1i6ALOr297GujieaHtMLZdkLa7RBKHCW+TORwtJHxNVJoGuf7m9rNzAP9huCipkZYz0Tj3hCgz2qqVBvQ4wXJRMQd0b5su8CWuihl4CcPYUaB0LfXAW6GTL7P5cjwBf61UMge8O8j6bdXXWWDGozhlA+ZMLYbr2i+JiRLoAOMfmPA/ahgIyZQFnCsst3fytLMarGv+7Tcgcg3pEZzXa4eA5paE7XpQztioeA0jv4oZ8vG7nwAZFN
  template:
    metadata:
      creationTimestamp: null
      name: geoip-secret
      namespace: monitoring
