apiVersion: v1
data:
    license-key: ENC[AES256_GCM,data:zN5pRQ==,iv:5VmW+X/2o6VNSFCcV74g8PIDK9MtJkc7H2oxUAOeVSY=,tag:eiPVH9fkDLqD93g6eE0adQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: geoip-secret
    namespace: monitoring
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd09MY0x0NWY3VWJwTW4z
            R3kwekUzZm05Q3V0N3AzTTVCYkxJdmx5TkdnCkVxd0Fud1VhcytFY2V3SkFZZXlJ
            aHgxY2pvcWZhWHkzQVlkRzBOWXdyc1EKLS0tIGF2eithcmRLNG5QTms1M3pUT2xk
            MFZHbjVWSTBmcVA3OUJGM2xOc1NLWEUK4AQ4y/jJTOhZQNvFsNiklUY7uK+SQv1R
            iClms1a6P7/tw5Sfp+4GksfuPGBh/joOWN0H4RzKzNy7eG8r3eD40A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T21:08:34Z"
    mac: ENC[AES256_GCM,data:Tb1MgqAfv9dWfEqShmcZ70j1GVdMIt2gokFwv2mFPijWkch1Xpa0mbm4iY+iEEUGpmZihtbLTcu2STjPjKPhsfm+X3VZfVK0DH2XhMdqBDg3NiXp5Izv45mvnBxpdQtL851q3x7MtTVKFtPcukNiPQHHK1rs9OxycOwisBkULRA=,iv:u9qy714QsJ90ZncSwX6r6JvnbUEWguzyXE49fjN5Hfw=,tag:ruBw3ApCDy9KCNe9pFJIQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
