---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    releaseName: promtail
    namespace: monitoring
    version: 6.16.6
    valuesFile: values.yaml

resources:
  - geoip-secret.sops.yaml
