apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbird
  namespace: network
spec:
  encryptedData:
    NB_SETUP_KEY: AgBp7GjgGK1HtLHtPC0pgVASIJo4mA6E4ugzCih57L0j7RwgatgXJkVJVJu87ojO1kbLzP3HN6+ZsdOvh+kvF528ssvKTDTJ+8em5Eha5VPSjQkd6lHB5M/R8Jhs4LG+Tfw5HSHYaozzV7q+rCGYQ3+2Ff+lmi619aLyzfN2gN4qMhAyQBHLALcQ5vlinTd5F0xbu7tCeIMDsL9rOY+Pi+/7g8bHuE1N6n/AjtTuxCmucX6Utk9U5aK1AQa2zU3WGajaulVvPTbrn07a0SzaXp/zqqeJa3JMI7t43xnKH6ATrDRgSykcWJ+n0m3EcNn5dGQ/Zuuf2dmg0RMiGmdWgv+f00cCke/Y1lEXAzt2MycyjStYi0OtnIQ7UnKeAKLdQVAlxgBG5uXFy4zhUtFfgQ5IkWGBnWV8eq3Qip5ABh7tfGSt0zmC7r4HJT3FRWqi5FD/x0rTySDBhGTtvCxKq/QUtGQVbQ48yPOZPIl3+Qpwa1iYyGXIc57bSdjvtmW4clSFUBFCoA6trZrJ7rJKlm05CvWQM8ei7s4g8lPBqsAYyfDevqHqXSF1YBszwynW08Ja/7PlqPc6Fyv1oVZVVm9mxkhMh015tfXLY5u1T92Rh9FYkHkqR4EzdWD7vMDVW60ALEHg3L7eIZSFio7jho5zNy6AB19/LfKU6HVnBehsozlVdpxkWvWUJZa7m+D+H4wJRPiMx1kyIzpJzTBjnodfEmrpVtbc2T/iCtfHrUx/y9RelpU=
  template:
    metadata:
      creationTimestamp: null
      name: netbird
      namespace: network

