apiVersion: v1
data:
    NB_SETUP_KEY: ENC[AES256_GCM,data:OlB0iA==,iv:iNtc+TDMoLOyJfgTYtiz6c1DusyxrwuwOiiAlDo3CO0=,tag:pCG+C8mXVfg2iGWR+RsiZQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: netbird
    namespace: network
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdS91WVpiUmxiNzVnUytV
            Mmg0S0hKS0V0Y2g4ZkE4TCtJd3F6U3RNRjFRClhpUjdqUWdJcU9XTDJMNytrek9n
            QVZzNFRPa3RTR1ZuLzlFdXM2ZnZkZTgKLS0tIE1rQ2FGT3pjZG9jTVc5UFIzMEdE
            MzdxaFdqK2VkdDBmVThHQXZGTTBmN1EKU4wrm74mDHZFmPPbqI59cokBaUVXxOUv
            56SKiy6VvWfmds5fAWUEUfQaXEYHFBeEdg6Hvg691L360/kh/cmKjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T21:08:34Z"
    mac: ENC[AES256_GCM,data:LgQcJo09fGGvVUQ2fGKpWiSG98XYksgOlYbDUCahayOa6mS6ayBZYUHoxQfEWAy7sXGZdacjCgdNINdweTwOniZHVlr2h4YG53dySswni8fRA2ZmoDMlNfwzpsRCwXVzMDNZrckmuQwOebM2wuB7fPPupczWDi6NFBIz44pIB7s=,iv:UsfOzOcIdaGwFeHUTHnpza6raoTG75gyWAP1GS7DhTg=,tag:AmD++O7uRsGudEfWhtrmDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
