apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbird-turn-secret
  namespace: network
spec:
  encryptedData:
    TURN_PASSWORD: AgBmkXsdxe+sViqHyWHt8qAoet94OLHJKbi156yGkno59rQYNeo8mtoOd3DP0LjUdiWCnEDZXiA9Zl2Vhq7NCxCMylpjo4sa34fzssxqEXyjqntXsj2DRc+3jxsOvJ+f7k80Y7f+WfahPQ3p4AGpxRN/Kzq8nLrtRFh43Js3dxeiVjtyNB6Oey6IH8BMbTSnFY8NRxF7YTB/DH/mZHsMwfp5kwwJpyoPAER12GlKJZDsCYdBwL2tifklgP9EN1Nq74kKpci5v+dl/vQUyK+Sa2/w2+XCbCxj6bdggdXokexVJ/2r4BHBKdOhPjUK4XPDrT5ZfTckyTwzKfZG/HRddQoREAzVmUl6Kti0CoddRca0vGMND4DsYtLuDmOY5BcOc7v1DzlB4HFisNko/3wCl6vyqUFls2u+BlBbsIGuKZNkpDtfhYC6A2UEGiOYdScLn72Bx8KW8tUhQyPIqmzwjOgtFhvoqEOEW0IME5jck/UjdNNKWceR0qR7zbFdBMZaTvKbYdR1CoaeF8RJTWhdZA/NuM/WuoSb+/TroQ9hlX3+treloAN3rGZgZSPbox9jKSDmwzSYRcwI2/FiT6p5her8d9AS71QDWmhG+ruUsD30uyNslaCW1He1uXhViShbWoK9fabGDTqZx+qwZ//GD+uad2v4K2AyJSb4sZ+vLXrnmvio5foY/ugk8yMpVQKVJQ83NCxkIWwNU00JSyw=
    TURN_USERNAME: AgCcbFnhIr4MOTXGLa16e+1w/cktNmd3H0f+LjcYmsliShXFcdlGpQZi8kRJzFKNHhymYiaFcCJA7EDkQJ4wM5Wg/UDQiETTvibc81WMRFNtNPYaBSf8Wv3F9ggJ+j6jz/2Xrryk3TV8LB98TwdVPVC9S5WN0KVeRmkPzyYGpPjZ4ftEKn13uPAuwKE256rTY00VWyYiJRR/48Ecbd4W1Bx17YMjH2H2rQfUb/ZnwXaBZOHGHch6L3QzPZ0NYObuptv65qHpVKtpx7O/ufXzUP/2/PVv8hIYfl71iJ0urnqx7TdgW2wxJeZRl4pXiN0k7Md7Yb8llmpmInbGf82v/9mMvDXW0YkOkYsL2X2rQggQy4JPdUjTMKUKxHsNQoS5Mkagwy1BlVa+oJe3siDEuzmGNQ5bgrLit/+WUm1mMKI5X6IsjDwlbjLQUxhq+HGEnyyv5rWadBiNP6P1CVjdiuqkxYgYTtyuO1igHZ00NueEbThCeZgOxHeDfAR1dneg5wNKjko5GtOXQSwCQ+/kdqQpMG53tgEpRwCAnARNFiK1JPsTS4xPIMJMi0mhs9JopfF0XZI2h6J1gwKrL5ZuPa5T+zHsY0Mn8H2ES2oecKtVjnNlVNtl7JzZ6B9GCFbHlSyxXBX0YwNZXa5/9mUNFFae0j0bSbbhFe9onOBRsk9hDw+ZPTodGndMFe24Hp2K8YOflt+I7SmZr8fa
  template:
    metadata:
      creationTimestamp: null
      name: netbird-turn-secret
      namespace: network

