---
workloadType: DaemonSet

image:
  repository: docker.io/netbirdio/netbird
  tag: "0.61.2"
  pullPolicy: IfNotPresent

envs:
  - NB_HOSTNAME: "orbit-nodes"
  - NB_LOG_LEVEL: "warn"

secretEnvs:
  - NB_SETUP_KEY: "AgCUxpknwMF/EnGtFed+1wYoD3uQzgIdftd2MIcmPsLem3C3N8tGwrMZBXzfhJCHqO8FIW0C0jxtC3wMKeaYjhrwNS4Xl8U2pA587RsnbJeJPV0SP2/piMCrlE1ARwsoolFyfzH2Bmq/wQU0jF8hbz4bTnv+Kbbjfl9y9QG8E1tubvWdN/fPt76pgwpF71gryaAODVHEEV9qovUPgP292QmmoBOYf+7pZdUuRRuQsBepbD9ADnTqdBJHfsQL5ight3nH3s2YP798/PYlM+aw9EhC3oF4Xaqf0J77sUHLmz9rT+1/Ijmbren/oyUYjtzwKQSktn/A7ZezPtswkCpxc+YE6z1UsbxCH1hEa8Oc2mRHCHz6WP4SoXv4p9VRKzhKTG2VOOSjba0GOPW5Zo0dfehWB1cMNqTZSfGC2LCD5fawQCviQpVseP6bWp6Zm7mbcfwArC6ljjEtUdnRLsoS1oCl5Z7wsOF3QGGjE1Ir0l2KS0sJjXK44RmzApTBA+Zd4Hb+B5fyTtfkxguNQdzFvNPLuhRFcpke6o9QB64U8k1t+bLSDp7hY0xqnuieo+dEYdgFlGgjCga8dG79IvFo95zphinX6NcnDuj9pRsPO4ynSvRFInC4rEFpNHV86KY622GpYOrIpl+eBHFPXrQJO5gK0Dwng+H5fAkg+2zMZq3SfgjEWXOnaxa3RNZeMH2Y3KknXTF+orhdYH44B6UQBfUJ3gCIAFunK/7riii48NM9yhyG5xU="

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - SYS_RESOURCE
      - SYS_ADMIN

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

health:
  enabled: false
