---
workloadType: DaemonSet

image:
  repository: docker.io/netbirdio/netbird
  tag: "0.61.2"
  pullPolicy: IfNotPresent

envs:
  - NB_HOSTNAME: "orbit-nodes"
  - NB_LOG_LEVEL: "warn"

secretEnvs:
  - NB_SETUP_KEY: ""

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - SYS_RESOURCE
      - SYS_ADMIN

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

health:
  enabled: false
