apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7QD/NbVUNjE/J9O7CZ7nZi5ZtfmvpsSfwZQ3b6WMinIdL+pJaqH7GQ==,iv:MbmQw3qTRoKLhXIZ/LxTZKcUJq26HCxWmdjs4IJSCGk=,tag:8EOUTeoY+gV3DkPi/E9EYw==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOU1MV05tS2o4SUdkakZ6
            dDEzYWl2UEs4Y0dXUDJNWjJ1YVA1NWN0cEFrCnY4aTd0R1ExcWFTaUlpZXBLc2ox
            b2tTbTM1Rmp4dU43eUplbGJGVEF2SW8KLS0tIERMYXByYS9GVlpQdmRkOVJ0TU9s
            Q09KZFJsVGR2YWZCZnFCQVpsditsWDAKkB1P/qn88Z4WDHINwa+A00bjSgyMwq7r
            BtPj1toIQV+rw3N/VSJkQFWUmFgGHpiLeNc6OXWbjtX44PPHiQyqkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T08:28:29Z"
    mac: ENC[AES256_GCM,data:hOnYZUPf4EDtZofAav+Lctju7YbcPlNIwOaw02sIVf7Loeg7hCkjrzBuPnAdjMTEHJnrePGHCLNRoi7N81OYQdJELWC4TWWBJz9C1o39SrjxNMuUPEXMbUGHCCqUYHog8f3cIqcJ0wkmfSdlYRpHU4NRiv+1dKQ5CSu6TO8nWhc=,iv:kW35qauWjfJrjLJ4C2wbV8+Bm0oV5DFWeW6q5mr6gsQ=,tag:DQCU/crB4LSHdjv961SiNg==,type:str]
    encrypted_regex: ^(api-token)$
    version: 3.11.0
