---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`obsidian.${SECRET_DOMAIN_0}`)
      kind: Rule
      middlewares:
        - name: oauth2-proxy-auth
          namespace: network
      services:
        - name: obsidian-nginx
          port: 80

  tls:
    certResolver: letsencrypt
