---
image: "ghcr.io/myrenic/radarr@sha256:1514a66c4f9d383eb6e6304f2591b0dc034c7917626bc66d2b6a8ddc2f1f5d27 "

ports:
  - name: main
    containerPort: 7878

envs:
  - TZ: "Europe/Amsterdam"
  - EXTERNAL_AUTH: "true"

ingress:
  host: radarr.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: authentik
      namespace: edge

pvcs:
  - name: radarr-config
    type: nfs
    server: 10.0.69.20
    path: /mnt/ssd_disk/config/radarr
    accessMode: ReadWriteMany
    size: 5Gi
    mountPath: /config
  - name: radarr-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
