---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: network
type: Opaque
stringData:
  password: REPLACE_ME
  secret-key: REPLACE_ME
  bootstrap-email: REPLACE_ME
  bootstrap-password: REPLACE_ME
  postgresql-password: REPLACE_ME
