applicationsets:
  main:
    name: main
    generators:
      - git:
          repoURL: https://github.com/myrenic/orbit.git
          revision: cleanup-root-dir
          directories:
            - path: kubernetes/**/*
    template:
      metadata:
        name: '{{path[1]}}-{{path.basenameNormalized}}'
      spec:
        project: default
        source:
          repoURL: https://github.com/myrenic/orbit.git
          targetRevision: cleanup-root-dir
          path: '{{path}}'
          plugin:
            name: kustomize-helm
            parameters:
              - name: NAMESPACE
                string: '{{path[1]}}'
        destination:
          name: in-cluster
          namespace: '{{path[1]}}'
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
            - FailOnSharedResource=true
            - ServerSideApply=true
        ignoreDifferences:
          - group: apiextensions.k8s.io
            kind: CustomResourceDefinition
            name: bgppeers.metallb.io
            jsonPointers:
              - /spec/conversion/webhook/clientConfig/caBundle
          - group: apiextensions.k8s.io
            kind: CustomResourceDefinition
            name: addresspools.metallb.io
            jsonPointers:
              - /spec/conversion/webhook/clientConfig/caBundle
