---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-sa
      containers:
        - name: traefik
          image: traefik:v3.5.2
          env:
            - name: CLOUDFLARE_DNS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token
                  key: api-token
            - name: ENROLL_KEY
              valueFrom:
                secretKeyRef:
                  name: crowdsec-api-token
                  key: ENROLL_KEY
            - name: TRAEFIK_BOUNCER_KEY
              valueFrom:
                secretKeyRef:
                  name: crowdsec-api-token
                  key: TRAEFIK_BOUNCER_KEY
          args:
            - --log.level=INFO
            - --log.format=json
            - --api.dashboard=true
            - --api.insecure=true
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --entrypoints.websecure.address=:443
            - --providers.kubernetesingress.ingressclass=traefik
            - --providers.kubernetesingress.ingressendpoint.hostname=tuntelder.com
            - --providers.kubernetescrd
            - --providers.kubernetescrd.allowCrossNamespace=true
            - --certificatesresolvers.letsencrypt.acme.email=38107502+Myrenic@users.noreply.github.com
            - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
            - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
            - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
            - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.version=v1.3.0"
            - --accesslog=true
            - --accesslog.filepath=/var/log/traefik/traefik.log
            - --accesslog.filters.statuscodes=100-599
            - --accesslog.format=json
            - --accesslog.fields.headers.defaultmode=keep
          ports:
            - containerPort: 80
              name: web
            - containerPort: 443
              name: websecure
            - containerPort: 8080
              name: admin
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: acme-storage
              mountPath: /data
            - name: acme-storage
              mountPath: /etc/traefik
            - name: crowdsec-api-token
              mountPath: /etc/crowdsec
              readOnly: true
            - name: traefik-logs
              mountPath: /var/log/traefik
      volumes:
        - name: acme-storage
          persistentVolumeClaim:
            claimName: traefik-acme-pvc
        - name: crowdsec-api-token
          secret:
            secretName: crowdsec-api-token
        - name: traefik-logs
          persistentVolumeClaim:
            claimName: traefik-logs-pvc
