---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-postgres-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/ssd_disk/config/authentik
    server: 10.0.69.20
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-pvc
  namespace: edge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: authentik-postgres-pv
  storageClassName: ""
