---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-cluster-secretsmanager
    kind: ClusterSecretStore
  target:
    name: immich-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: authentik_postgres-password
        property: password
