---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin-password
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-cluster-secretsmanager
    kind: ClusterSecretStore
  target:
    name: argocd-admin-password
  data:
    - secretKey: secretValue
      remoteRef:
        key: argocdAccountAdmin
