apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBtL3XpQDs6w6hhY7QSIArCX1GBUU6EzsJ476oPnu3B3CEKnbzgzEsxepFhIMSGt8A++cH1IDPzCSBbFSPV6BFn9URmdbSzYKFN2ZK9mge5mYxXpTuW11Lo17nJh3iCCaeroIX1Et2rzRLq+sf6GsjjoLsO+Huqu5eBQTkMESAiOSRR0P5uaEHx4y6G/3rT/pugTnnz5wnjhSTqeuax/Mi1qnKerGMUlE5trKk89PpJGWNOvsnNra/BkFIlhoKEkJOTmlXLqT5ImwJ5H7E2RHBU5xqtTvoj5H28NbDLQceSBpD1PT0yLbdepRlxaHvCzLHuEtN4MCDzyM8DlYzIkEKuv5Cd5/T8U785EN8MVwTqs1a62gJNyi9UEXVDlkLx9jmeARpubKNvqscHl229/kqlfmsUxwwgwJE2d9eh9Z9vNfphyLTiHKRkIQAO2JYquyfjzgtno1/T1oZNRcSNea9uv6S5tjFPLheldXAy9JWKiGEBwKne5UjWekGvYXJY85m/zkeEbJdd1DDJ/ueHAmtD2uSADRX7jDmub7fiBFlTseauSno5eVpa+KXfv9AJEg06fgCsBrYduWrle+Ef3ksCGKKuNQMoCxL2BBGIMKXE87dWsfxCo6Hhu0zaVigOa9EoRz38vDlJW6nIGmifxldoMY5NG+96i//Y+PbkUoELXRwq6HOoNQEPa82NoRcIHi3JrRmKqu4I09nb8as=
    admin-user: AgAaohj6/R47SosL+8GQ30vss9FE7HfbxavSdsAcn7zwyyPrZuQFbikT21A2yvpl6mnT4yzoPXgT7EZZaKNNPRdlpcgBj/LNDLPpyYju0cD8P8JNDGHMORef0J1/lS24NIGQbvXDd/kAKd3x6i8KaBSRLRL+TXYQLNJ617iv2ixXSylFu/gSgELfOGAX+8QD3EUtME9lx8wT8BY6v7CDpyhG+WDJosxwyXH7LNMvaWXXwSNchgJnNa0wBKMVdZseT3JP3nZ2P2lgZsiUgdRO3sjCvIMOPGMuCNyTrDPL7YVdIqzSG7gm7Et5lfNCxPmdfUaACqJxXkf6xXHOJV2Ayo7bUlKFFqndUkaKs6E9oVSX54jpksUr7H1g/ivrZnXYLCmBr7XiPC8oESSNsJ66/fX19zwLfR2ZoKXn4cOKJEZ9UtN7iErRNfzJ5qdOKMAO6QXr11+4vOnQigFtm19Fi/tOXCSxZXErlgInBWWVEGiWWx04c2RwBZQOIPj5D4j36X7tKUsjE8oF85ZDxCDB/VFTQ36ZX9Ov3V6aK0BSgBjCcLVr+V8ZMOCSWi1r4Vzlw8WYfignbFuDdHAYj1a/g1beEHBHoYAzvVHing/g+6X+vZrpR0SshWM6VHERN9iYASgNkGO7ILfE9n0H1vZ2Mgl2HMhiE0QYvhbS61cqojKtTA8ZRSS6Ko+mHP0E7llmzTeR2I6e+++V2zpD
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring

