---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBujWpfcX/HccUJTGMRsKoExPMd1xe2SN8JAm7jfJi5M+q3e8Si7Xe71VP8mrNvganpjqAsG01AAwMQaq7MQbOBEuYxH0MTsAORjgOQUb3KgMlW5OhG+tMdc6iFGWJ5bFp86gbv3lsYbJMpv1okz9s7qvOQucqi8FD7iS9JMvpwDtSkO3aX2zJXRetIOZNsBx3oBoxUVqgc7wNSa4ck+r3ExkyhKeaSMxPAVaiJknS5MVvxOr4ZZVytjj1JNvxIHrdI1Oc6cegWqvboZFuu8w9s9gCXuZHKMYSZtuluyUTUy9tedp+EUm9abhvrSX8/kxnifVFysDuSPwdGMlR4de2yKVtHlIbrwPOQfzUS5RERY8kDGImsP70As7D2ORh9j5CKDhSlzyt93cIn9H7/bQzVKrCpC78tnj82DuMbLXyO+FTLOygoRDZAghxuWO3HFmqLnXd8+vOpSgSN/jehso4iitbWjZ1sr9qBfayqi3g99ERS7l9kHevqUaxhHKuje2rD7s/8EzuoOox1FK7ChWQtL8IRkQl96TFct6v/HNXziyyjIxI1WstUFqPWn0NW0WADGFg+QIv/OYiaHJboniLijJFOAkC9nrnzw0pwKP8RKX9b0JwwE81yyb2xzZwCfXgvXpX9DnwOVH/pF98e3Qt0fux0wG2Z9nHRFQ2+i+5MaAemtLWeHW9b8Kc2VQ8w8ysLgF5B0KwzhmCdnxg=
    admin-user: AgCDio6EmAVz29M0lNOavVTzjffsCedq6c29jcuZfCVhw+BEOA3OavI3ppOEqpLtIed+eDADWECdZmJOP+t6hJSGX9HkBNfvyR8OMeRH1g3EPbqFky9vUOdedh4NcosGSc6yS0iYH2e7Oj+CCCu7LIMBt1ZntBzNdh5z5pianyAvX7QRQXYhefZfmSpXGETHVf5Ke3GqyiS5Gm83nbltT53zN1s0h2PiMB1n/qLCyCaug2sBWF0zHNSuum8imQROJPLtnp2wVyHlEDPgKOv5KUVHBLej09sA4pujbXRg14C7bYiaBlOn12QVgTRPAmcbshVD0EiidcSZEySEU6mPWPOly9WuFywmBdfswN2X+j7KkWcE/hmwXEvKnRQy4MS3mepOnpT7Xd5fBIf/cV3PeJ5nsQA/h/ZPZpGXBTrx/jJJrsLPDpd6XAeszkPBoZLw+taMoLmkkyu7zrQ5KzcqwpGp8QEa7IluaqYhMFx0hbPMr7KdQeyjwJ3+dOOlbTl/5nS6vpwW+5IxIiqMufbeV01cbKw3pqWIB3kQ9hH2s2ZDaZQCwpzokkhgNf6Zp65qNtT85GUMsr6AnwYNkhImxQzAD0YC9gyDOvkUGyZJTH7S77EVXJ39/zti7yDrA7xYWOPltzWavTJ7uaUN9M0Qu0CEWNDQ4aX8dvROiez5uFbxopJDOURaMEs2YQp3BAiO8PHGiI634aGS5xQhDKI=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
