apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCuiiWOIj/K6arfQognETrroZGDIcXtirmuajKv/q2AgZPX2NqL1x28Tgph/jwpfEJsjI56/a9WNkIeSfmAlwOIiwzNnnN7nBb/D9fvYfpsnkWaWdOrmbKgW2aPWVwdO15WCMEqf3u74K9pX5TiqYW5hsduTgLjP4xOW24O4n6T7RWfZhasLV/BQTXWzZDOX27MByBkoeVWv0gUCNr+WL1E/ti8gW9Is2V3PoaE2dlk1GXuoVIYgKIi1it2GqKd3dJLjHplcI9VVwSiyZH3AA76Awd06gZNYuHjw3YXrs5H73h8FZmsmk6OLxcRWVxzWPi76ffKbs1m6x7NZPkNv63+clFSa9yF1HjlDYMYMgwy/Vx9XhDI0oVb6Oyeno1cB/0HcVxLko3YBWthnsNfY6Ee+0eACSpzA/ffHlxMK7+KpEORgMzaTMLlLB1Yo1Nl4J2tbwkV41vkk+Va3CCoXEO+Pg5g2OvAiPmaYuBHrsOtKMBrVM+E1PdQ/ssVuM34Pi/B2bDTpsAFORoYEq/ygM7o0iMN6/ClsuGUC9808EikNtl1bz10dRaB0M9U4W0azosQySmDVXiFE1TxI1zu04pPx3p7S9Y+52GoHXAi95hy9/N5x+VyS/qXV4ve3RWrLbHg5aqDpoo3MqbPZdubhr3U+GD7CIuZWmsvKprWohi3sWrNm3CNeLcItKNpP90YBc3SNuI9GvzTCerpSjI=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring

