apiVersion: v1
kind: Secret
metadata:
    name: hello-world-secret
    namespace: hello-world
type: Opaque
stringData:
    greeting: ENC[AES256_GCM,data:Kiorq0ROOdPC/2s=,iv:p/NkpLqixR+Eb8YWjmCNpGfJareA++N/XVjuJSVDFFc=,tag:6hogeVgrZEbrSXvrnWIJQg==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDJxWnF3dlRlRFNqMjJn
            OGdYbXowQWxVVEpuVDJvSEV4Zi9iTWtJYWpnCjJ4NTBuVXFsYXJQZ1ZXaXhJY0N2
            MHhWOUZsVTFqaWQ5NWR0a1loRGwxOTQKLS0tIGZlZkJ6bUFxQUVrK2VRZFE3L3V1
            YlkyZ1B5WmZCcUV5dVNQZktXaGp4ZkEK3D9u0nFolE0HbxvXSGgh0z9FG6jksJfn
            HvMCQmsmxoMLzgv5JBFY6lSVqs5DGepHMxu5HdLZlmi+Vhac8W22lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T05:54:32Z"
    mac: ENC[AES256_GCM,data:YmCtriNV2zh3Q09zdgDhko1z38+9yEoHZ+K4IwhTMmja1TnXBzqVVLaGn9e1ld5xkO/rYuO/T3USNYRqtucVj2pKC7VnFy9g9F244rB4b7O6C6kIhNU0XiWnVZEaAYSZVDpbZQ8h+mQSwNZLARvSNT90W15TUh+glzJZbJwOaBw=,iv:bau+mxZ+K7v/NUaiyodAXvY6IL9F8qCD5Gajikd4ys0=,tag:CPu2NAU1ZVxkyTZQtwLwgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
