apiVersion: v1
kind: Secret
metadata:
    name: hello-world-secret
    namespace: hello-world
type: Opaque
stringData:
    greeting: ENC[AES256_GCM,data:7+D/qSms9CB3T0QQO1Rgh4x7zNQB9HsuGqC2GpqzJ3zOwST5+u09H+US,iv:yqK+FPGO0OBwtHhFt3bMQZ/PgZ1tDr7yIbx38MdpPg0=,tag:qmLgfHMc+ZVsHXLBBrKdDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t0md7g4f79yldwj2qwllkzfkhh9zs6n4grzg47wl20hk2gf7grsz4lmvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Um5nSWwxT0RKdlFDZmpD
            dE1aTE5hMlVJZzFFSngxTEhrQUJ4WWZ6dmw0CkZWZ3RjUE4zd0E3K2VMOEFNWVhI
            U3hzTlVDU0UxTDIvSzc0NVgwK3ZJckEKLS0tIEpmZ1FTNVZSemFoTWR1TVFOVGND
            dUJ4ZGpPZHFsaTdyTU1YbkY2REQwV1EKrNCEjn3oXSe/Lm3tKfVojEEAsJHK0e05
            dAs1Y5nnVOsiktcBuc1i7RXUVRSBLfrwT24V26Q9c54ujNLwSwOK2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T20:55:13Z"
    mac: ENC[AES256_GCM,data:NRadbNnrBuSC3WHMMQo5Y+3pWUsI9e1EoIPPxFugrn4P3PbGrIRyogF4chBZKIlSG5Uy+/LOshVEBYuRpw0wx9RgyYNAyBs4R+YZ8PD1yFsMqiCprQ2BjyPQauk+fIUJhPrc/M+6J4eaKmETAEpDa+hucXiSEiMtSEVLHkLiVys=,iv:4jxVC2eu37Mt1MfeP2Th2Y9VB94wxv1826nMAn38yzU=,tag:lIcxjoSaFzfLcWIG8m3jaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
