apiVersion: v1
kind: Secret
metadata:
    name: hello-world-secret
    namespace: hello-world
type: Opaque
stringData:
    greeting: ENC[AES256_GCM,data:B5AL1YoiMuE6N7DN1ISYgu6T6cU+6nSlT87AuT844EqsNa47NMtUO+FV,iv:2ePL2XrS51ZJS+mvZuR+aPK4qCtAuGTo6T+gOvF+JPk=,tag:RUJnOCJ3qsT10k7/om/EUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t0md7g4f79yldwj2qwllkzfkhh9zs6n4grzg47wl20hk2gf7grsz4lmvt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTnZ6S1BiYnlVbXZ0TDE3
            M2RrSU5mMHhXRXBFK2xmOHVKL25oNnFIc1ZFCkx1T0ZsMkJDc3FvVDA4ZU9SRWdk
            UjJHckcrMldNQytJdXFqYnVySFNtMmcKLS0tIHZHU2hHU2hJYm5hRG1tTkd6MHQ4
            ellRUG5FemRKZDZ0dTk1RnVTOUFUUHcKGQuIsxSXCEuLt+O/eF1lA+a20vO24S21
            7NcHljQouTxpvL3mLTte8jo36nenOSPL9QEnh7IciRd1CkDIvMRqvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T20:22:23Z"
    mac: ENC[AES256_GCM,data:t/17ScciSmKKy8ZF9JQwFcrYiClAxR8cLTVc3X2PDP8GwU/TmrYiQiDrQGtHEYTgCnOOWud81AqI68dUwtPQtI3y4A7xEg9oK+xJI66xNfWte2VkIuLLZwh7a6cm4vhu9oNoOXrP0iQuLE+/nC2AYvlu/5hbtfR4SQIXVWEeJ/M=,iv:LkgkLxaudAyKWbdA/Wlk5h1yKAXfBm7eYd9Hpg6PS+o=,tag:j+IC5wO58+tcaqMERF07Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
