---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: network
    version: v1.19.1
    valuesFile: values.yaml

resources:
  - ./base/ClusterIssuer.yaml
