---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.tuntelder.com`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
      middlewares:
        - name: crowdsec-mw
          namespace: edge
        - name: authentik
          namespace: edge
  tls:
    certResolver: letsencrypt
