# Disable unnecessary components for a lightweight setup
grafana:
  enabled: false  # you already deploy Grafana separately

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    replicas: 1
    retention: 7d
    storageSpec:
      emptyDir: {}  # or configure persistent volume if needed

alertmanager:
  alertmanagerSpec:
    replicas: 1

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

coreDns:
  enabled: false

namespaceOverride: monitoring

prometheusOperator:
  admissionWebhooks:
    enabled: false