crds:
  enabled: true

defaultRules:
  create: true
  rules:
    kubeProxy: false
    windows: false

grafana:
  enabled: false
kubeProxy:
  enabled: false

nodeExporter:
  enabled: false
  operatingSystems:
    linux:
      enabled: false
    darwin:
      enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 30d

prometheusOperator:
  admissionWebhooks:
    enabled: false

