---
image: "ghcr.io/home-operations/prowlarr:2.1.5.5216"

ports:
  - name: main
    containerPort: 9696

ingress:
  host: prowlarr.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: authentik
      namespace: edge

pvcs:
  - name: prowlarr-config
    type: nfs
    server: 10.0.69.20
    path: /mnt/ssd_disk/config/prowlarr
    accessMode: ReadWriteMany
    size: 5Gi
    mountPath: /config


podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
